name: Go API Diff
on: 
  pull_request:
jobs:
  go-apidiff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version: 1.21.x
    - uses: joelanford/go-apidiff@main
